# Generated by Django 5.2.17 on 2026-09-10 17:52

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=80)),
                ('last_name', models.CharField(blank=True, max_length=80)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('counselor', 'Counselor'), ('financial_admin', 'Financial administrator'), ('counselee', 'Counselee')], max_length=20)),
                ('timezone_name', models.CharField(blank=True, max_length=64)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('mfa_required', models.BooleanField(default=False)),
                ('allow_magic_link', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Django admin access flag. Not related to the ministry staff roles.')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'indexes': [models.Index(fields=['role'], name='accounts_us_role_1fa9a5_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('role__in', ['admin', 'counselor', 'financial_admin', 'counselee'])), name='user_role_is_known'), models.CheckConstraint(condition=models.Q(('allow_magic_link', True), ('role__in', ['admin', 'counselor', 'financial_admin']), _negated=True), name='staff_may_not_use_magic_link')],
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
    ]
