# Generated by Django 5.2.17 on 2026-09-10 23:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('byte_size', models.BigIntegerField()),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('storage_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('wrapped_dek', models.BinaryField()),
                ('dek_nonce', models.BinaryField()),
                ('scan_status', models.CharField(choices=[('clean', 'Clean'), ('infected', 'Infected'), ('skipped', 'Not scanned')], max_length=20)),
                ('scan_detail', models.CharField(blank=True, max_length=200)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='messaging.message')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['message', 'id'], name='messaging_m_message_41b11f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('byte_size__gt', 0)), name='message_attachment_is_not_empty'), models.CheckConstraint(condition=models.Q(('scan_status', 'infected'), _negated=True), name='infected_attachments_are_never_stored')],
            },
        ),
    ]
