# Generated by Django 5.2.17 on 2026-09-11 02:45

import apps.billing.models
import apps.core.dates
import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counseling', '0002_alter_case_opened_on_alter_casemember_joined_on'),
        ('scheduling', '0003_alter_availabilityrule_effective_from'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('processed', 'Processed'), ('ignored', 'Ignored — not an event we act on'), ('duplicate', 'Duplicate delivery'), ('failed', 'Failed')], max_length=20)),
                ('detail', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Stripe event',
                'ordering': ['-received_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('session', 'Counseling session'), ('late_cancellation', 'Late cancellation'), ('no_show', 'Missed appointment')], max_length=30)),
                ('amount_cents', models.IntegerField(help_text='Zero is allowed and means this is not charged for.')),
                ('effective_from', models.DateField(default=apps.core.dates.org_today)),
                ('effective_to', models.DateField(blank=True, help_text='Leave blank while this rate is current.', null=True)),
                ('counselor', models.ForeignKey(blank=True, help_text="Leave blank for the ministry's standard rate.", limit_choices_to={'role': 'counselor'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['kind', 'counselor', '-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Sent, awaiting payment'), ('paid', 'Paid'), ('void', 'Voided'), ('uncollectible', 'Written off')], db_index=True, default='draft', max_length=20)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('due_on', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default=apps.billing.models.default_currency, editable=False, max_length=3)),
                ('total_cents', models.IntegerField(default=0)),
                ('amount_paid_cents', models.IntegerField(default=0)),
                ('memo', models.CharField(blank=True, max_length=200)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=200)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='counseling.case')),
                ('counselee', models.ForeignKey(help_text='Who is being billed. One invoice is addressed to one person.', limit_choices_to={'role': 'counselee'}, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to=settings.AUTH_USER_MODEL)),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices_raised', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices_voided', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_cents', models.IntegerField()),
                ('method', models.CharField(choices=[('card', 'Card'), ('cash', 'Cash'), ('check', 'Check'), ('bank_transfer', 'Bank transfer')], max_length=20)),
                ('received_on', models.DateField(default=apps.core.dates.org_today)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.invoice')),
                ('recorded_by', models.ForeignKey(blank=True, help_text='Null for a payment that arrived through Stripe.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_recorded', to=settings.AUTH_USER_MODEL)),
                ('reverses', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='billing.payment')),
            ],
            options={
                'ordering': ['-received_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SessionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('occurred_on', models.DateField(default=apps.core.dates.org_today)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=60)),
                ('kind', models.CharField(choices=[('session', 'Counseling session'), ('late_cancellation', 'Late cancellation'), ('no_show', 'Missed appointment')], default='session', max_length=30)),
                ('fee_cents', models.IntegerField(default=0)),
                ('is_billable', models.BooleanField(default=True, help_text='Untick for a session the ministry is not charging for.')),
                ('waived_reason', models.CharField(blank=True, max_length=200)),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='session_record', to='scheduling.booking')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_records', to='counseling.case')),
                ('counselee', models.ForeignKey(help_text='Who the session was for, and who is billed for it.', limit_choices_to={'role': 'counselee'}, on_delete=django.db.models.deletion.PROTECT, related_name='sessions_received', to=settings.AUTH_USER_MODEL)),
                ('counselor', models.ForeignKey(limit_choices_to={'role': 'counselor'}, on_delete=django.db.models.deletion.PROTECT, related_name='sessions_delivered', to=settings.AUTH_USER_MODEL)),
                ('fee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='billing.fee')),
                ('recorded_by', models.ForeignKey(blank=True, help_text='Null when the record was raised automatically from a booking.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('unit_amount_cents', models.IntegerField()),
                ('amount_cents', models.IntegerField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.invoice')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='billing.sessionrecord')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_customer_id', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('counselee', models.OneToOneField(limit_choices_to={'role': 'counselee'}, on_delete=django.db.models.deletion.PROTECT, related_name='stripe_customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stripe customer',
            },
        ),
        migrations.AddIndex(
            model_name='fee',
            index=models.Index(fields=['kind', 'effective_from'], name='billing_fee_kind_a3493e_idx'),
        ),
        migrations.AddConstraint(
            model_name='fee',
            constraint=models.CheckConstraint(condition=models.Q(('amount_cents__gte', 0)), name='fee_is_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='fee',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='fee_effective_range_is_ordered'),
        ),
        migrations.AddConstraint(
            model_name='fee',
            constraint=models.UniqueConstraint(condition=models.Q(('counselor__isnull', False)), fields=('kind', 'counselor', 'effective_from'), name='uniq_counselor_fee_per_date'),
        ),
        migrations.AddConstraint(
            model_name='fee',
            constraint=models.UniqueConstraint(condition=models.Q(('counselor__isnull', True)), fields=('kind', 'effective_from'), name='uniq_ministry_fee_per_date'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['case', '-issued_on'], name='billing_inv_case_id_3fadfd_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['counselee', 'status'], name='billing_inv_counsel_17882e_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'due_on'], name='billing_inv_status_19be28_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('total_cents__gte', 0)), name='invoice_total_is_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid_cents__gte', 0)), name='invoice_paid_is_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['open', 'paid', 'uncollectible']), _negated=True), ('issued_on__isnull', False), _connector='OR'), name='an_issued_invoice_has_a_date'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'void'), _negated=True), models.Q(('voided_at__isnull', False), models.Q(('void_reason', ''), _negated=True)), _connector='OR'), name='a_void_invoice_says_when_and_why'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('due_on__isnull', True), ('issued_on__isnull', True), ('due_on__gte', models.F('issued_on')), _connector='OR'), name='invoice_is_not_due_before_it_is_issued'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice', '-received_on'], name='billing_pay_invoice_e6929b_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount_cents', 0), _negated=True), name='payment_is_not_zero'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('reverses__isnull', True), ('amount_cents__lt', 0), _connector='OR'), name='a_reversal_is_negative'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('stripe_payment_intent_id', ''), _negated=True), fields=('stripe_payment_intent_id',), name='uniq_stripe_payment_intent'),
        ),
        migrations.AddIndex(
            model_name='sessionrecord',
            index=models.Index(fields=['case', '-occurred_on'], name='billing_ses_case_id_fbb4ac_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionrecord',
            index=models.Index(fields=['counselee', '-occurred_on'], name='billing_ses_counsel_9165ee_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionrecord',
            index=models.Index(fields=['counselor', '-occurred_on'], name='billing_ses_counsel_45bc98_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionrecord',
            index=models.Index(fields=['is_billable', '-occurred_on'], name='billing_ses_is_bill_0c639b_idx'),
        ),
        migrations.AddConstraint(
            model_name='sessionrecord',
            constraint=models.CheckConstraint(condition=models.Q(('fee_cents__gte', 0)), name='session_fee_is_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='sessionrecord',
            constraint=models.CheckConstraint(condition=models.Q(('is_billable', True), models.Q(('waived_reason', ''), _negated=True), _connector='OR'), name='an_unbilled_session_says_why'),
        ),
        migrations.AddConstraint(
            model_name='sessionrecord',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__gt', 0)), name='session_has_a_duration'),
        ),
        migrations.AddIndex(
            model_name='invoicelineitem',
            index=models.Index(fields=['invoice', 'id'], name='billing_inv_invoice_df80de_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoicelineitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='line_quantity_is_positive'),
        ),
        migrations.AddConstraint(
            model_name='invoicelineitem',
            constraint=models.CheckConstraint(condition=models.Q(('amount_cents', django.db.models.expressions.CombinedExpression(models.F('quantity'), '*', models.F('unit_amount_cents')))), name='line_total_is_quantity_times_unit'),
        ),
        migrations.AddConstraint(
            model_name='invoicelineitem',
            constraint=models.UniqueConstraint(condition=models.Q(('session__isnull', False)), fields=('invoice', 'session'), name='uniq_session_per_invoice'),
        ),
    ]
