# Generated by Django 5.2.17 on 2026-09-11 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoice_number_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrecord',
            name='needs_pricing',
            field=models.BooleanField(default=False),
        ),
    ]
