# Generated by Django 5.2.17 on 2026-09-11 16:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.CharField(blank=True, help_text='For example smtp.gmail.com.', max_length=255)),
                ('port', models.PositiveIntegerField(default=587)),
                ('use_tls', models.BooleanField(default=True, help_text='STARTTLS on port 587. Leave this on unless your provider says otherwise.')),
                ('username', models.CharField(blank=True, help_text='The mailbox that sends. For Google Workspace, the full address.', max_length=255)),
                ('from_email', models.EmailField(blank=True, help_text='What recipients see in the From line. Usually the same address.', max_length=254)),
                ('storage_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('wrapped_dek', models.BinaryField(blank=True, null=True)),
                ('dek_nonce', models.BinaryField(blank=True, null=True)),
                ('password_sealed', models.BinaryField(blank=True, null=True)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_error', models.CharField(blank=True, max_length=300)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mail settings',
                'verbose_name_plural': 'mail settings',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='mail_settings_is_a_singleton')],
            },
        ),
    ]
