# Generated by Django 5.2.17 on 2026-09-11 18:48

from django.conf import settings
from django.db import migrations, models


def choose_a_transport_security(apps, schema_editor):
    """Give the existing row one of the two, so the constraint below can hold.

    Until now `use_tls` was a plain checkbox, so a row could be saved with it
    off and nothing in its place — which is a mailbox password sent in the
    clear. Port 465 is implicit TLS everywhere it is offered; anything else gets
    STARTTLS, which is what the environment fallback has always used.
    """
    MailSettings = apps.get_model('core', 'MailSettings')
    for row in MailSettings.objects.filter(use_tls=False, use_ssl=False):
        if row.port == 465:
            row.use_ssl = True
        else:
            row.use_tls = True
        row.save(update_fields=['use_tls', 'use_ssl'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mailsettings',
            name='use_ssl',
            field=models.BooleanField(default=False, help_text='Implicit TLS, usually on port 465. Offered instead of STARTTLS.'),
        ),
        migrations.AlterField(
            model_name='mailsettings',
            name='host',
            field=models.CharField(blank=True, help_text='For example smtp.gmail.com, or smtp.zoho.com.', max_length=255),
        ),
        migrations.AlterField(
            model_name='mailsettings',
            name='use_tls',
            field=models.BooleanField(default=True, help_text='STARTTLS, usually on port 587.'),
        ),
        migrations.AlterField(
            model_name='mailsettings',
            name='username',
            field=models.CharField(blank=True, help_text='The mailbox that sends. Usually the full address.', max_length=255),
        ),
        migrations.RunPython(choose_a_transport_security, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='mailsettings',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('use_ssl', False), ('use_tls', True)), models.Q(('use_ssl', True), ('use_tls', False)), _connector='OR'), name='mail_settings_one_transport_security'),
        ),
    ]
