# Generated by Django 5.2.17 on 2026-09-14 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(editable=False, max_length=10, unique=True, verbose_name='reference')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(help_text='What a counselor would call it. “Handling anxious thoughts”.', max_length=200)),
                ('summary', models.TextField(blank=True, help_text='What it is, and when you would reach for it. Searched with the title.')),
                ('topics', models.CharField(blank=True, help_text='Comma separated, in whatever words you would search for: anxiety, grief.', max_length=200)),
                ('kind', models.CharField(choices=[('handout', 'Handout or worksheet'), ('article', 'Article or reading'), ('book', 'Book or booklet'), ('training', 'Training or talk'), ('other', 'Other')], default='other', max_length=20)),
                ('url', models.URLField(blank=True, help_text='A link to the article, video or shop page, if there is one.', max_length=500)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('byte_size', models.BigIntegerField(blank=True, null=True)),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('storage_key', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('wrapped_dek', models.BinaryField(blank=True, null=True)),
                ('dek_nonce', models.BinaryField(blank=True, null=True)),
                ('scan_status', models.CharField(blank=True, choices=[('clean', 'Clean'), ('infected', 'Infected'), ('skipped', 'Not scanned')], max_length=20)),
                ('scan_detail', models.CharField(blank=True, max_length=200)),
                ('contributed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_resources', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [],
            },
        ),
        migrations.CreateModel(
            name='ResourceComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(editable=False, max_length=10, unique=True, verbose_name='reference')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_comments', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='knowledge.resource')),
            ],
            options={
                'ordering': ['created_at'],
                'permissions': [],
            },
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['-created_at'], name='knowledge_r_created_a6e0f5_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['kind'], name='knowledge_r_kind_b42fe7_idx'),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('url', ''), _negated=True), ('storage_key__isnull', False), _connector='OR'), name='knowledge_resource_has_a_file_or_a_link'),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('storage_key__isnull', True), ('wrapped_dek__isnull', True)), models.Q(('storage_key__isnull', False), ('wrapped_dek__isnull', False)), _connector='OR'), name='knowledge_resource_file_is_whole'),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.CheckConstraint(condition=models.Q(('byte_size__isnull', True), ('byte_size__gt', 0), _connector='OR'), name='knowledge_resource_file_is_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.CheckConstraint(condition=models.Q(('scan_status', 'infected'), _negated=True), name='infected_resources_are_never_stored'),
        ),
        migrations.AddIndex(
            model_name='resourcecomment',
            index=models.Index(fields=['resource', 'created_at'], name='knowledge_r_resourc_bc88e0_idx'),
        ),
    ]
