# Generated by Django 5.2.17 on 2026-09-10 19:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counseling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('visibility', models.CharField(choices=[('private', 'Only me and my counselor'), ('case_shared', 'Everyone on this case')], default='private', help_text='Who on the case may see this, besides the counselor.', max_length=20)),
                ('kind', models.CharField(choices=[('intake', 'Intake paperwork'), ('homework', 'Homework or worksheet'), ('handout', 'Handout or reading'), ('correspondence', 'Correspondence'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('byte_size', models.BigIntegerField()),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('storage_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('wrapped_dek', models.BinaryField()),
                ('dek_nonce', models.BinaryField()),
                ('thumbnail_key', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('thumbnail_wrapped_dek', models.BinaryField(blank=True, null=True)),
                ('thumbnail_dek_nonce', models.BinaryField(blank=True, null=True)),
                ('scan_status', models.CharField(choices=[('clean', 'Clean'), ('infected', 'Infected'), ('skipped', 'Not scanned')], max_length=20)),
                ('scan_detail', models.CharField(blank=True, max_length=200)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='counseling.case')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(help_text='Who uploaded it. Not who it is about.', on_delete=django.db.models.deletion.PROTECT, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [],
                'indexes': [models.Index(fields=['case', '-created_at'], name='documents_d_case_id_d92db7_idx'), models.Index(fields=['owner', '-created_at'], name='documents_d_owner_i_13f3b4_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('byte_size__gt', 0)), name='document_is_not_empty'), models.CheckConstraint(condition=models.Q(('scan_status', 'infected'), _negated=True), name='infected_documents_are_never_stored'), models.CheckConstraint(condition=models.Q(('thumbnail_key__isnull', True), ('thumbnail_wrapped_dek__isnull', False), _connector='OR'), name='thumbnail_has_a_key')],
            },
        ),
    ]
