# Generated by Django 5.2.17 on 2026-09-11 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('scheduling', '0003_alter_availabilityrule_effective_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='booking',
            field=models.ForeignKey(blank=True, help_text='The appointment this was uploaded for, if it was for one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='scheduling.booking'),
        ),
    ]
