# Generated by Django 5.2.17 on 2026-09-14 16:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_public_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(editable=False, max_length=10, unique=True, verbose_name='reference')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(help_text='What a counselor will look for. “Personal Data Inventory”, not “PDI-v3”.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='What it is for, and when to use it. Searched along with the name.')),
                ('kind', models.CharField(choices=[('intake', 'Intake paperwork'), ('homework', 'Homework or worksheet'), ('handout', 'Handout or reading'), ('correspondence', 'Correspondence'), ('other', 'Other')], default='other', max_length=20)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('byte_size', models.BigIntegerField()),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('storage_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('wrapped_dek', models.BinaryField()),
                ('dek_nonce', models.BinaryField()),
                ('thumbnail_key', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('thumbnail_wrapped_dek', models.BinaryField(blank=True, null=True)),
                ('thumbnail_dek_nonce', models.BinaryField(blank=True, null=True)),
                ('scan_status', models.CharField(choices=[('clean', 'Clean'), ('infected', 'Infected'), ('skipped', 'Not scanned')], max_length=20)),
                ('scan_detail', models.CharField(blank=True, max_length=200)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'permissions': [],
                'indexes': [models.Index(fields=['name'], name='documents_d_name_ee5c4d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('byte_size__gt', 0)), name='document_template_is_not_empty'), models.CheckConstraint(condition=models.Q(('scan_status', 'infected'), _negated=True), name='infected_templates_are_never_stored'), models.CheckConstraint(condition=models.Q(('thumbnail_key__isnull', True), ('thumbnail_wrapped_dek__isnull', False), _connector='OR'), name='template_thumbnail_has_a_key')],
            },
        ),
    ]
