# Generated by Django 5.2.17 on 2026-09-10 18:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('label', models.CharField(help_text='How staff refer to this case, e.g. “Smith — marriage”.', max_length=120)),
                ('kind', models.CharField(choices=[('individual', 'Individual'), ('couple', 'Couple'), ('family', 'Family')], default='individual', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_hold', 'On hold'), ('closed', 'Closed')], default='active', max_length=20)),
                ('opened_on', models.DateField(default=django.utils.timezone.localdate)),
                ('closed_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('counselor', models.ForeignKey(limit_choices_to={'is_active': True, 'role': 'counselor'}, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opened_on', 'label'],
            },
        ),
        migrations.CreateModel(
            name='CaseMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('joined_on', models.DateField(default=django.utils.timezone.localdate)),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='counseling.case')),
                ('counselee', models.ForeignKey(limit_choices_to={'role': 'counselee'}, on_delete=django.db.models.deletion.PROTECT, related_name='case_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CounseleeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=120)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=32)),
                ('referred_by', models.CharField(blank=True, max_length=120)),
                ('intake_completed_on', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'counselee'}, on_delete=django.db.models.deletion.CASCADE, related_name='counselee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'counselee profile',
            },
        ),
        migrations.CreateModel(
            name='CounselorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credentials', models.CharField(blank=True, help_text='e.g. “ACBC Certified”. Shown to counselees.', max_length=120)),
                ('bio', models.TextField(blank=True)),
                ('default_session_minutes', models.PositiveSmallIntegerField(default=60)),
                ('booking_notice_hours', models.PositiveSmallIntegerField(default=24, help_text='Minimum notice a counselee must give when booking.')),
                ('booking_horizon_days', models.PositiveSmallIntegerField(default=60, help_text='How far ahead counselees may book.')),
                ('accepting_new_cases', models.BooleanField(default=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'counselor'}, on_delete=django.db.models.deletion.CASCADE, related_name='counselor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['counselor', 'status'], name='counseling__counsel_502aa6_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status', '-opened_on'], name='counseling__status_939ad2_idx'),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.CheckConstraint(condition=models.Q(('closed_on__isnull', True), ('closed_on__gte', models.F('opened_on')), _connector='OR'), name='case_closed_on_after_opened_on'),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'closed'), _negated=True), ('closed_on__isnull', False), _connector='OR'), name='closed_case_has_a_closed_date'),
        ),
        migrations.AddIndex(
            model_name='casemember',
            index=models.Index(fields=['counselee', 'case'], name='counseling__counsel_8cc03c_idx'),
        ),
        migrations.AddConstraint(
            model_name='casemember',
            constraint=models.UniqueConstraint(fields=('case', 'counselee'), name='uniq_case_counselee'),
        ),
        migrations.AddConstraint(
            model_name='casemember',
            constraint=models.CheckConstraint(condition=models.Q(('ended_on__isnull', True), ('ended_on__gte', models.F('joined_on')), _connector='OR'), name='membership_ended_after_joined'),
        ),
        migrations.AddConstraint(
            model_name='counselorprofile',
            constraint=models.CheckConstraint(condition=models.Q(('default_session_minutes__gte', 15), ('default_session_minutes__lte', 480)), name='session_length_is_plausible'),
        ),
    ]
