# Generated by Django 5.2.17 on 2026-09-11 01:19

import apps.core.dates
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='opened_on',
            field=models.DateField(default=apps.core.dates.org_today),
        ),
        migrations.AlterField(
            model_name='casemember',
            name='joined_on',
            field=models.DateField(default=apps.core.dates.org_today),
        ),
    ]
