# Generated by Django 5.2.17 on 2026-09-10 20:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('google_email', models.EmailField(max_length=254)),
                ('calendar_id', models.CharField(default='primary', max_length=255)),
                ('granted_scopes', models.TextField(blank=True)),
                ('include_names', models.BooleanField(default=False, help_text='Off by default. Anyone who can see your calendar — on a shared screen, or a phone notification — would see the name.', verbose_name='Show counselee names in my Google calendar')),
                ('block_slots_from_calendar', models.BooleanField(default=True, help_text='Only free/busy is read — bcTracker never sees the titles or the people in your other appointments.', verbose_name='Hide times when I am busy in Google')),
                ('storage_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('wrapped_dek', models.BinaryField()),
                ('dek_nonce', models.BinaryField()),
                ('refresh_token_sealed', models.BinaryField()),
                ('access_token_sealed', models.BinaryField(blank=True, null=True)),
                ('access_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=300)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('counselor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_credential', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Google calendar connection',
            },
        ),
    ]
