# Generated by Django 5.2.17 on 2026-09-11 01:19

import apps.core.dates
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_google_credential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilityrule',
            name='effective_from',
            field=models.DateField(default=apps.core.dates.org_today),
        ),
    ]
