# Generated by Django 5.2.17 on 2026-09-11 21:05

import apps.scheduling.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_booking_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='meeting_url',
            field=models.URLField(blank=True, help_text='Optional. A https:// link the counselee can click to join.', max_length=500, validators=[apps.scheduling.models.validate_meeting_link], verbose_name='Meeting link'),
        ),
        migrations.AddField(
            model_name='booking',
            name='series_key',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
