# Generated by Django 5.2.17 on 2026-09-10 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_email', models.EmailField(blank=True, help_text='Snapshot taken at the time of the action; not affected by later edits.', max_length=254)),
                ('actor_role', models.CharField(blank=True, max_length=20)),
                ('verb', models.CharField(db_index=True, max_length=60)),
                ('target_type', models.CharField(blank=True, max_length=60)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('case_id_snapshot', models.CharField(blank=True, max_length=64)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=36)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Null for actions taken by scheduled jobs rather than a person.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'default_permissions': ('add', 'view'),
                'indexes': [models.Index(fields=['target_type', 'target_id', '-created_at'], name='audit_audit_target__19f19a_idx'), models.Index(fields=['actor', '-created_at'], name='audit_audit_actor_i_fb4253_idx'), models.Index(fields=['case_id_snapshot', '-created_at'], name='audit_audit_case_id_a4c137_idx')],
            },
        ),
    ]
